name: NBA Twitter Bot

on:
 schedule:
    - cron: '0 6 * * *' # Daily at midnight UTC
 workflow_dispatch: {}

jobs:
  debug-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment variables
        run: |
          echo "TWITTER_APP_KEY is set: ${TWITTER_APP_KEY:+set}"
          echo "TWITTER_APP_SECRET is set: ${TWITTER_APP_SECRET:+set}"
          echo "TWITTER_ACCESS_TOKEN is set: ${TWITTER_ACCESS_TOKEN:+set}"
          echo "TWITTER_ACCESS_SECRET is set: ${TWITTER_ACCESS_SECRET:+set}"
          echo "Rapid_API_KEY is set: ${Rapid_API_KEY:+set}"
  env:
    TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
    TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
    TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
    TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
    Rapid_API_KEY: ${{ secrets.RAPID_API_KEY }}

  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Verify nba-bot.js content
        run: |
          echo "First 20 lines of nba-bot.js:"
          head -n 20 nba-bot.js

      - name: Debug environment variables
        run: |
          echo "TWITTER_APP_KEY is set: ${TWITTER_APP_KEY:+set}"
          echo "TWITTER_APP_SECRET is set: ${TWITTER_APP_SECRET:+set}"
          echo "TWITTER_ACCESS_TOKEN is set: ${TWITTER_ACCESS_TOKEN:+set}"
          echo "TWITTER_ACCESS_SECRET is set: ${TWITTER_ACCESS_SECRET:+set}"
          echo "Rapid_API_KEY is set: ${RAPID_API_KEY:+set}"
        env:
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          Rapid_API_KEY: ${{ secrets.RAPID_API_KEY }}

      - name: Run the bot
        env:
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          Rapid_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: node -e "require('./nba-bot').postNBATweets().then(() => { console.log('Tweets posted'); process.exit(0); }).catch(err => { console.error(err); process.exit(1); })"
