name: NBA Bot

# Trigger the workflow daily at 12:00 UTC or manually via workflow_dispatch
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Debug environment variables (shows if secrets are set, masks values)
      - name: Debug environment
        run: |
          echo "Checking environment variables..."
          echo "RAPIDAPI_KEY: ${RAPIDAPI_KEY:0:4}... (masked)"
          echo "TWITTER_APP_KEY: ${TWITTER_APP_KEY:0:4}... (masked)"
          echo "TWITTER_APP_SECRET: ${TWITTER_APP_SECRET:0:4}... (masked)"
          echo "TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN:0:4}... (masked)"
          echo "TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET:0:4}... (masked)"
          echo "Node modules installed:"
          ls -l node_modules | head -n 10

      # Run the NBA bot
      - name: Run NBA Tweet Bot
        env:
          NODE_ENV: production
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          node -e "require('./nba-bot').postNBATweets().then(() => { console.log('Tweets posted'); process.exit(0); }).catch(err => { console.error('Error:', err.message, err.stack); process.exit(1); })"